package com.example.recruitment_website.entities;

import java.time.LocalDate;
<<<<<<< HEAD
import java.time.LocalDateTime;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotNull;

@Entity
@Table(name = "Job")
=======
import java.util.Date;

import com.example.recruitment_website.enums.EmploymentType;
import com.example.recruitment_website.enums.JobLevel;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name = "Job")
@Getter
@Setter
>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
public class JobEntity {

    @Id
    private String id;

<<<<<<< HEAD
    @NotNull
    private String employerId;

    @Column(nullable = false, name= "title")
    private String title;

    @Column(name = "salary")
    private String salary;

    @Column(name = "experience")
    private String experience;

    @Column(name = "department")
    private String department;

=======
    @ManyToOne
    @JoinColumn(name = "employer_uid", referencedColumnName = "uid", nullable = false)
    private EmployerEntity employer;

    private String title;
    private String salary;
    private String experience;

>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(columnDefinition = "TEXT")
    private String requirements;

    @Column(columnDefinition = "TEXT")
    private String benefits;

<<<<<<< HEAD
    @Column(name = "deadline")
    private LocalDate deadline;

    @Column(name = "remote_ok")
    private Boolean remoteOk;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "status")
    private String status;

    @Column(name = "number_of_vacancies")
    private Integer numberOfVacancies;

    @Column(name = "job_level")
    private String jobLevel;

    @Column(name = "employment_type")
    private String employmentType;

    public JobEntity() {
    }

=======
    private LocalDate deadline;

    @Column(nullable = false, updatable = false)
    private Date createdAt;

    private Date updatedAt;

    private String status;

    private Integer numberOfVacancies;

    @Enumerated(EnumType.STRING)
    private JobLevel jobLevel;

    @Enumerated(EnumType.STRING)
    private EmploymentType employmentType;

    private String city;
    private String country;
    private String address;
    private String workingHours;

    @Column(nullable = false)
    private Boolean isApproved;

    @Column(nullable = false)
    private Integer applicationCount;

    @PrePersist
    protected void onCreate() {
        Date now = new Date();
        createdAt = now;
        updatedAt = now;
        if (status == null) {
            status = "OPEN";
        }
        if (numberOfVacancies == null) {
            numberOfVacancies = 1;
        }
        if (isApproved == null) {
            isApproved = false;
        }
        if (applicationCount == null) {
            applicationCount = 0;
        }
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = new Date();
    }

    public JobEntity() {}

    public JobEntity(String id, EmployerEntity employer, String title, String salary, String experience,
                     String description, String requirements, String benefits, LocalDate deadline,
                     JobLevel jobLevel, EmploymentType employmentType, String city, String country,
                     String address, String workingHours) {
        this.id = id;
        this.employer = employer;
        this.title = title;
        this.salary = salary;
        this.experience = experience;
        this.description = description;
        this.requirements = requirements;
        this.benefits = benefits;
        this.deadline = deadline;
        this.jobLevel = jobLevel;
        this.employmentType = employmentType;
        this.city = city;
        this.country = country;
        this.address = address;
        this.workingHours = workingHours;
    }

    // Getters and Setters can be generated by Lombok annotations
    // or manually defined if needed
>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

<<<<<<< HEAD
    public String getEmployerId() {
        return employerId;
    }

    public void setEmployerId(String employerId) {
        this.employerId = employerId;
=======
    public EmployerEntity getEmployer() {
        return employer;
    }

    public void setEmployer(EmployerEntity employer) {
        this.employer = employer;
>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getSalary() {
        return salary;
    }

    public void setSalary(String salary) {
        this.salary = salary;
    }

    public String getExperience() {
        return experience;
    }

    public void setExperience(String experience) {
        this.experience = experience;
    }

<<<<<<< HEAD
    public String getDepartment() {
        return department;
    }

    public void setDepartment(String department) {
        this.department = department;
    }

=======
>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getRequirements() {
        return requirements;
    }

    public void setRequirements(String requirements) {
        this.requirements = requirements;
    }

    public String getBenefits() {
        return benefits;
    }

    public void setBenefits(String benefits) {
        this.benefits = benefits;
    }

    public LocalDate getDeadline() {
        return deadline;
    }

    public void setDeadline(LocalDate deadline) {
        this.deadline = deadline;
    }

<<<<<<< HEAD
    public Boolean getRemoteOk() {
        return remoteOk;
    }

    public void setRemoteOk(Boolean remoteOk) {
        this.remoteOk = remoteOk;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

=======
    public Date getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }


>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Integer getNumberOfVacancies() {
        return numberOfVacancies;
    }

    public void setNumberOfVacancies(Integer numberOfVacancies) {
        this.numberOfVacancies = numberOfVacancies;
    }

<<<<<<< HEAD
    public String getJobLevel() {
        return jobLevel;
    }

    public void setJobLevel(String jobLevel) {
        this.jobLevel = jobLevel;
    }

    public String getEmploymentType() {
        return employmentType;
    }

    public void setEmploymentType(String employmentType) {
        this.employmentType = employmentType;
    }
=======
    public JobLevel getJobLevel() {
        return jobLevel;
    }

    public void setJobLevel(JobLevel jobLevel) {
        this.jobLevel = jobLevel;
    }

    public EmploymentType getEmploymentType() {
        return employmentType;
    }

    public void setEmploymentType(EmploymentType employmentType) {
        this.employmentType = employmentType;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getWorkingHours() {
        return workingHours;
    }

    public void setWorkingHours(String workingHours) {
        this.workingHours = workingHours;
    }

    public Boolean getIsApproved() {
        return isApproved;
    }

    public void setIsApproved(Boolean isApproved) {
        this.isApproved = isApproved;
    }

    public Integer getApplicationCount() {
        return applicationCount;
    }

    public void setApplicationCount(Integer applicationCount) {
        this.applicationCount = applicationCount;
    }

>>>>>>> 54bd3df142c5d84d5be09e1d494e215c82fd8f86
}
